<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <!-- Logo/nome do Sistema-->
        <div class="navbar nav_title" style="border: 0;">
            <a href="<?php echo UrlRequestHelper::mountUrl('Index', "index");?>" class="site_title">
                <i class="fa fa-heart"></i>
                <span>Segue-me M/D</span>
            </a>
        </div>
        <div class="clearfix"></div>
        <!-- / Logo/nome do Sistema-->

        <!-- informações de usuario -->
        <div class="profile">
            <div class="profile_pic">
                <?php $SECURITY = SecurityHelper::getInstancia(); $view_userLogado = $SECURITY->getUsuario(); ?>
                <img src="<?php echo $view_userLogado->getUrlImagem();?>" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Bem Vindo,</span>
                <h2><?php echo $view_userLogado->getNome();?></h2>
            </div>
        </div>
        <!-- /nformações de usuario -->

        <br />

        <!-- Sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

            <div class="menu_section">
                <h3> &nbsp;</h3>
                <ul class="nav side-menu">
                    <li>
                        <a href="<?php echo UrlRequestHelper::mountUrl('Index', "index")?>" >
                            <i class="fa fa-home"></i> 
                            Principal 
                        </a>
                    </li>
                    <li>
                        <a>
                            <i class="fa  fa-edit"></i> 
                            Publicações 
                            <span class="fa fa-chevron-down"></span>
                        </a>
                        <ul class="nav child_menu" style="display: none">
                            <li>
                                <a href="<?php echo UrlRequestHelper::mountUrl('Publicacao', "listar")?>">
                                    Listar Todas
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo UrlRequestHelper::mountUrl('Publicacao', "cadastrar")?>">
                                    Nova Publicação
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="<?php echo UrlRequestHelper::mountUrl('Usuarios', "index")?>">
                            <i class="fa  fa-users"></i> 
                            Usuarios 
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <!-- / Sidebar menu -->

        <!-- rodape sidebar -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Se">
                Se
            </a>
            <a data-toggle="tooltip" data-placement="top" title="gue">
                gue
            </a>
            <a data-toggle="tooltip" data-placement="top" title="me" >
                me
            </a>
            <a data-toggle="tooltip" data-placement="top" title="M/D">
                M/D
            </a>
        </div>
        <!-- /rodape sidebar -->
    </div>
</div>

<!-- topo -->
<div class="top_nav">

    <div class="nav_menu">
        <nav class="" role="navigation">
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="<?php echo UrlRequestHelper::mountUrlPost('Usuario', "deslogar")?>" class="user-profile">
                        Sair &nbsp; <i class="fa fa-sign-out "></i> 
                    </a>
                </li>
            </ul>
        </nav>
    </div>

</div>
<!-- /topo -->