<script src="<?php echo PATH_TEMPLATE_JS_URL ?>bootstrap.min.js"></script>
<script src="<?php echo PATH_TEMPLATE_JS_URL ?>progressbar/bootstrap-progressbar.min.js"></script>
<script src="<?php echo PATH_TEMPLATE_JS_URL ?>nicescroll/jquery.nicescroll.min.js"></script>
<script src="<?php echo PATH_TEMPLATE_JS_URL ?>icheck/icheck.min.js"></script>
<script src="<?php echo PATH_TEMPLATE_JS_URL ?>custom.js"></script>