<div id="wrapper">
    <div id="login" class="animate form">
        <section class="login_content login_center">
            <form method="post" action="<?php echo UrlRequestHelper::mountUrlGet('Usuario', 'logar')?>" >
                <h1>Login</h1>
                <div>
                    <input type="email" class="form-control" name="email" placeholder="Insira seu E-mail" required="" />
                </div>
                <div>
                    <input type="password" class="form-control" name="senha " placeholder="INsira sua Senha" required="" />
                </div>
                <div>
                    <input class="btn btn-default submit" type="submit" value="Entrar"/>
                    <a class="reset_pass" href="<?php echo UrlRequestHelper::mountUrl('Logon', 'esqueceuSenha')?>">Esqueceu sua Senha?</a>
                </div>
                <div class="clearfix"></div>
                <div class="separator">

                    <p class="change_link">Novo por aqui?
                        <a href="<?php echo UrlRequestHelper::mountUrl('Logon', 'registrar')?>" class="to_register"> Registre-se </a>
                    </p>
                    <div class="clearfix"></div>
                    <br />
                    <div>
                        <h1><i class="fa fa-beer" style="font-size: 26px;"></i> PubApp!</h1>

                        <p>Todos os Direitos Reservados © 2015 </p>
                    </div>
                </div>
            </form>
            <!-- form -->
        </section>
        <!-- content -->
    </div>
</div>