<div class="two-forms">
    <div class="wrap">
        <br>
        <div class="login">
            <h2 style="text-align: center;">Segue-me M/D - Alterar Senha</h2>
            <?php if($view_erro): ?>
                <div class="error">
                    <label for="inputError1">Ops, Algo errado Aconteceu. Por favor Contate o Administrador.</label>
                </div> <br>
            <?php endif; ?>
            <?php if($view_erroConfirmacao): ?>
                <div class="error">
                    <label for="inputError1">Ops, Senhas não conferem. Por favor tente Novamente.</label>
                </div> <br>
            <?php endif; ?>
            <?php if($view_erroSenha): ?>
                <div class="error">
                    <label for="inputError1">Ops, Senha incorreta. Por favor Tente novamente.</label>
                </div> <br>
            <?php endif; ?>
            <?php if($view_success): ?>
                <div class="success">
                    <label for="inputError1">Alterações realizadas com Sucesso.</label>
                </div> <br>
            <?php endif; ?>
            <div class="login-info">
                <form id="fEdita" method="post" action="index.php?Request/post/l/Usuario/a/alterarSenha">
                    <div class="users">
                        <input name="id" type="hidden" value="<?php echo $view_id;?>"/>
                        <input name="senhaAtual" type="password" class="text" placeholder="Insira sua Senha Atual" required="">
                        <input name="senha" type="password" class="text" placeholder="Insira sua Nova Senha" minlength="6" maxlength="18" required="">
                        <input name="confirmacao" type="password" class="text" placeholder="Confirme sua Nove Senha" minlength="6" maxlength="18" required="">
                    </div>
                    <div class="btns">
                        <input type="submit" value="Salvar" >
                    </div>
                </form>
                <div class="clear"> </div>
            </div>
        </div>
        <div class="clear"> </div>
    </div>
</div>
<div class="copy-right">
    <p><a href="http://seguememd.com.br" target="_blank">Segue-me M/D</a> &copy; 2016 | Todos os Direitos Reservados</p>
</div>