<div class="col-md-12">
    <div class="col-middle">
        <div class="text-center text-center" style="margin-top: 16%; color: #fcc11a;">
            <h1 class="error-number"><?php echo $view_erro; ?></h1>
            <h2><?php echo $view_detalhes; ?></h2>
            <p>
                Desculpe pelos transtornos, <a href="#">Clique Aqui</a> 
                e nos informe o ocorrido para que possamos concertar o mais rapido possivel.
            </p>
        </div>
    </div>
</div>